url: https://riacheruvu.github.io
baseurl: /109A_Final_Project/

# Site settings
title: spotiFire - 109A
email: riacheruvu@g.harvard.edu
description: "This is our CS109A Final Project"


# Team names, titles and social links
people:

- name: Guido Camps
  pic: 1
  position: Position Here
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Sunil Chomal
  pic: 2
  position: Position Here
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Ria Cheruvu
  pic: 3
  position: Master's Student in Data Science
  social:
    - title: github
      url: https://github.com/riacheruvu

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#social:
#  - title: twitter
#    url: http://twitter.com/jekyllrb
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket 
#    url: http://bitbucket.org/jekyll
#  - title: github
#    url: http://github.com/jekyll

# Build settings
markdown: kramdown
permalink: pretty
